### ISSUE TITLE
Update `mdi-svg` dependency to `@mdi/svg`

### ISSUE THREAD

**Issue by Templarian** [release-notes/release-notes-hub#45]
Currently it looks like this project is using `v2.1.19`. When you update to the latest version. Please ensure to switch the dependency for `mdi-svg` to the `@mdi/svg` package. Which is on `v2.2.43`.

Thanks!

We'll be deprecating `mdi-svg` shortly.

**Comment by alrik** [comment]
A nice, thanks for your notice @Templarian .
I'll update the deps soon - and thank you so much for your super awesome mdi project :bowing_man: 

Do you maintain a changelog or some other form of release-notes at your mdi project, yet?
This project aims for easy broadcasting of release announcements to your community.
Maybe there are some synergies.

**Comment by Templarian** [comment]
We'll be looking into things like that shortly. Right now we use twitter and will be managing more first party integrations shortly to ensure everyone is on the latest. The goal eventually is to send the page below in a formatted email after each release.

https://materialdesignicons.com/history
The dev server is easier to read... http://dev.materialdesignicons.com/history
